// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module guidedfilter204 (
        I_enhanced_data_stream_V_din,
        I_enhanced_data_stream_V_full_n,
        I_enhanced_data_stream_V_write,
        ONES_V_V_dout,
        ONES_V_V_empty_n,
        ONES_V_V_read,
        I_V_V_dout,
        I_V_V_empty_n,
        I_V_V_read,
        I_2_V_V_dout,
        I_2_V_V_empty_n,
        I_2_V_V_read,
        I_COPY_V_V_dout,
        I_COPY_V_V_empty_n,
        I_COPY_V_V_read,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [15:0] I_enhanced_data_stream_V_din;
input   I_enhanced_data_stream_V_full_n;
output   I_enhanced_data_stream_V_write;
input  [31:0] ONES_V_V_dout;
input   ONES_V_V_empty_n;
output   ONES_V_V_read;
input  [31:0] I_V_V_dout;
input   I_V_V_empty_n;
output   I_V_V_read;
input  [31:0] I_2_V_V_dout;
input   I_2_V_V_empty_n;
output   I_2_V_V_read;
input  [31:0] I_COPY_V_V_dout;
input   I_COPY_V_V_empty_n;
output   I_COPY_V_V_read;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    boxfilter200205_U0_ap_start;
wire    boxfilter200205_U0_ap_done;
wire    boxfilter200205_U0_ap_continue;
wire    boxfilter200205_U0_ap_idle;
wire    boxfilter200205_U0_ap_ready;
wire    boxfilter200205_U0_start_out;
wire    boxfilter200205_U0_start_write;
wire    boxfilter200205_U0_ONES_V_V_read;
wire   [31:0] boxfilter200205_U0_N_V_V_din;
wire    boxfilter200205_U0_N_V_V_write;
wire    boxfilter201206_U0_ap_start;
wire    boxfilter201206_U0_ap_done;
wire    boxfilter201206_U0_ap_continue;
wire    boxfilter201206_U0_ap_idle;
wire    boxfilter201206_U0_ap_ready;
wire    boxfilter201206_U0_I_V_V_read;
wire   [31:0] boxfilter201206_U0_mean_I_V_V_din;
wire    boxfilter201206_U0_mean_I_V_V_write;
wire    boxfilter202207_U0_ap_start;
wire    boxfilter202207_U0_ap_done;
wire    boxfilter202207_U0_ap_continue;
wire    boxfilter202207_U0_ap_idle;
wire    boxfilter202207_U0_ap_ready;
wire    boxfilter202207_U0_I_2_V_V_read;
wire   [31:0] boxfilter202207_U0_mean_II_V_V_din;
wire    boxfilter202207_U0_mean_II_V_V_write;
wire    compute_a_b208_U0_ap_start;
wire    compute_a_b208_U0_start_full_n;
wire    compute_a_b208_U0_ap_done;
wire    compute_a_b208_U0_ap_continue;
wire    compute_a_b208_U0_ap_idle;
wire    compute_a_b208_U0_ap_ready;
wire    compute_a_b208_U0_start_out;
wire    compute_a_b208_U0_start_write;
wire    compute_a_b208_U0_N_V_V_read;
wire   [31:0] compute_a_b208_U0_N_COPY_V_V_din;
wire    compute_a_b208_U0_N_COPY_V_V_write;
wire    compute_a_b208_U0_mean_I_V_V_read;
wire    compute_a_b208_U0_mean_II_V_V_read;
wire   [31:0] compute_a_b208_U0_a_V_V_din;
wire    compute_a_b208_U0_a_V_V_write;
wire   [31:0] compute_a_b208_U0_b_V_V_din;
wire    compute_a_b208_U0_b_V_V_write;
wire    boxfilter203209_U0_ap_start;
wire    boxfilter203209_U0_ap_done;
wire    boxfilter203209_U0_ap_continue;
wire    boxfilter203209_U0_ap_idle;
wire    boxfilter203209_U0_ap_ready;
wire    boxfilter203209_U0_a_V_V_read;
wire   [31:0] boxfilter203209_U0_mean_A_V_V_din;
wire    boxfilter203209_U0_mean_A_V_V_write;
wire    boxfilter210_U0_ap_start;
wire    boxfilter210_U0_ap_done;
wire    boxfilter210_U0_ap_continue;
wire    boxfilter210_U0_ap_idle;
wire    boxfilter210_U0_ap_ready;
wire    boxfilter210_U0_b_V_V_read;
wire   [31:0] boxfilter210_U0_mean_B_V_V_din;
wire    boxfilter210_U0_mean_B_V_V_write;
wire    compute_I_enhanced21_U0_ap_start;
wire    compute_I_enhanced21_U0_ap_done;
wire    compute_I_enhanced21_U0_ap_continue;
wire    compute_I_enhanced21_U0_ap_idle;
wire    compute_I_enhanced21_U0_ap_ready;
wire   [15:0] compute_I_enhanced21_U0_I_enhanced_data_stream_V_din;
wire    compute_I_enhanced21_U0_I_enhanced_data_stream_V_write;
wire    compute_I_enhanced21_U0_mean_A_V_V_read;
wire    compute_I_enhanced21_U0_mean_B_V_V_read;
wire    compute_I_enhanced21_U0_N_COPY_V_V_read;
wire    compute_I_enhanced21_U0_I_COPY_V_V_read;
wire    ap_sync_continue;
wire    N_V_V_full_n;
wire   [31:0] N_V_V_dout;
wire    N_V_V_empty_n;
wire    mean_I_V_V_full_n;
wire   [31:0] mean_I_V_V_dout;
wire    mean_I_V_V_empty_n;
wire    mean_II_V_V_full_n;
wire   [31:0] mean_II_V_V_dout;
wire    mean_II_V_V_empty_n;
wire    N_COPY_V_V_full_n;
wire   [31:0] N_COPY_V_V_dout;
wire    N_COPY_V_V_empty_n;
wire    a_V_V_full_n;
wire   [31:0] a_V_V_dout;
wire    a_V_V_empty_n;
wire    b_V_V_full_n;
wire   [31:0] b_V_V_dout;
wire    b_V_V_empty_n;
wire    mean_A_V_V_full_n;
wire   [31:0] mean_A_V_V_dout;
wire    mean_A_V_V_empty_n;
wire    mean_B_V_V_full_n;
wire   [31:0] mean_B_V_V_dout;
wire    mean_B_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_boxfilter200205_U0_ap_ready;
wire    ap_sync_boxfilter200205_U0_ap_ready;
reg   [1:0] boxfilter200205_U0_ap_ready_count;
reg    ap_sync_reg_boxfilter201206_U0_ap_ready;
wire    ap_sync_boxfilter201206_U0_ap_ready;
reg   [1:0] boxfilter201206_U0_ap_ready_count;
reg    ap_sync_reg_boxfilter202207_U0_ap_ready;
wire    ap_sync_boxfilter202207_U0_ap_ready;
reg   [1:0] boxfilter202207_U0_ap_ready_count;
reg    ap_sync_reg_compute_I_enhanced21_U0_ap_ready;
wire    ap_sync_compute_I_enhanced21_U0_ap_ready;
reg   [1:0] compute_I_enhanced21_U0_ap_ready_count;
wire   [0:0] start_for_compute_a_b208_U0_din;
wire    start_for_compute_a_b208_U0_full_n;
wire   [0:0] start_for_compute_a_b208_U0_dout;
wire    start_for_compute_a_b208_U0_empty_n;
wire    boxfilter201206_U0_start_full_n;
wire    boxfilter201206_U0_start_write;
wire    boxfilter202207_U0_start_full_n;
wire    boxfilter202207_U0_start_write;
wire   [0:0] start_for_boxfilter203209_U0_din;
wire    start_for_boxfilter203209_U0_full_n;
wire   [0:0] start_for_boxfilter203209_U0_dout;
wire    start_for_boxfilter203209_U0_empty_n;
wire   [0:0] start_for_boxfilter210_U0_din;
wire    start_for_boxfilter210_U0_full_n;
wire   [0:0] start_for_boxfilter210_U0_dout;
wire    start_for_boxfilter210_U0_empty_n;
wire    boxfilter203209_U0_start_full_n;
wire    boxfilter203209_U0_start_write;
wire    boxfilter210_U0_start_full_n;
wire    boxfilter210_U0_start_write;
wire    compute_I_enhanced21_U0_start_full_n;
wire    compute_I_enhanced21_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_boxfilter200205_U0_ap_ready = 1'b0;
#0 boxfilter200205_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_boxfilter201206_U0_ap_ready = 1'b0;
#0 boxfilter201206_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_boxfilter202207_U0_ap_ready = 1'b0;
#0 boxfilter202207_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_compute_I_enhanced21_U0_ap_ready = 1'b0;
#0 compute_I_enhanced21_U0_ap_ready_count = 2'd0;
end

boxfilter200205 boxfilter200205_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxfilter200205_U0_ap_start),
    .start_full_n(start_for_compute_a_b208_U0_full_n),
    .ap_done(boxfilter200205_U0_ap_done),
    .ap_continue(boxfilter200205_U0_ap_continue),
    .ap_idle(boxfilter200205_U0_ap_idle),
    .ap_ready(boxfilter200205_U0_ap_ready),
    .start_out(boxfilter200205_U0_start_out),
    .start_write(boxfilter200205_U0_start_write),
    .ONES_V_V_dout(ONES_V_V_dout),
    .ONES_V_V_empty_n(ONES_V_V_empty_n),
    .ONES_V_V_read(boxfilter200205_U0_ONES_V_V_read),
    .N_V_V_din(boxfilter200205_U0_N_V_V_din),
    .N_V_V_full_n(N_V_V_full_n),
    .N_V_V_write(boxfilter200205_U0_N_V_V_write)
);

boxfilter201206 boxfilter201206_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxfilter201206_U0_ap_start),
    .ap_done(boxfilter201206_U0_ap_done),
    .ap_continue(boxfilter201206_U0_ap_continue),
    .ap_idle(boxfilter201206_U0_ap_idle),
    .ap_ready(boxfilter201206_U0_ap_ready),
    .I_V_V_dout(I_V_V_dout),
    .I_V_V_empty_n(I_V_V_empty_n),
    .I_V_V_read(boxfilter201206_U0_I_V_V_read),
    .mean_I_V_V_din(boxfilter201206_U0_mean_I_V_V_din),
    .mean_I_V_V_full_n(mean_I_V_V_full_n),
    .mean_I_V_V_write(boxfilter201206_U0_mean_I_V_V_write)
);

boxfilter202207 boxfilter202207_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxfilter202207_U0_ap_start),
    .ap_done(boxfilter202207_U0_ap_done),
    .ap_continue(boxfilter202207_U0_ap_continue),
    .ap_idle(boxfilter202207_U0_ap_idle),
    .ap_ready(boxfilter202207_U0_ap_ready),
    .I_2_V_V_dout(I_2_V_V_dout),
    .I_2_V_V_empty_n(I_2_V_V_empty_n),
    .I_2_V_V_read(boxfilter202207_U0_I_2_V_V_read),
    .mean_II_V_V_din(boxfilter202207_U0_mean_II_V_V_din),
    .mean_II_V_V_full_n(mean_II_V_V_full_n),
    .mean_II_V_V_write(boxfilter202207_U0_mean_II_V_V_write)
);

compute_a_b208 compute_a_b208_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_a_b208_U0_ap_start),
    .start_full_n(compute_a_b208_U0_start_full_n),
    .ap_done(compute_a_b208_U0_ap_done),
    .ap_continue(compute_a_b208_U0_ap_continue),
    .ap_idle(compute_a_b208_U0_ap_idle),
    .ap_ready(compute_a_b208_U0_ap_ready),
    .start_out(compute_a_b208_U0_start_out),
    .start_write(compute_a_b208_U0_start_write),
    .N_V_V_dout(N_V_V_dout),
    .N_V_V_empty_n(N_V_V_empty_n),
    .N_V_V_read(compute_a_b208_U0_N_V_V_read),
    .N_COPY_V_V_din(compute_a_b208_U0_N_COPY_V_V_din),
    .N_COPY_V_V_full_n(N_COPY_V_V_full_n),
    .N_COPY_V_V_write(compute_a_b208_U0_N_COPY_V_V_write),
    .mean_I_V_V_dout(mean_I_V_V_dout),
    .mean_I_V_V_empty_n(mean_I_V_V_empty_n),
    .mean_I_V_V_read(compute_a_b208_U0_mean_I_V_V_read),
    .mean_II_V_V_dout(mean_II_V_V_dout),
    .mean_II_V_V_empty_n(mean_II_V_V_empty_n),
    .mean_II_V_V_read(compute_a_b208_U0_mean_II_V_V_read),
    .a_V_V_din(compute_a_b208_U0_a_V_V_din),
    .a_V_V_full_n(a_V_V_full_n),
    .a_V_V_write(compute_a_b208_U0_a_V_V_write),
    .b_V_V_din(compute_a_b208_U0_b_V_V_din),
    .b_V_V_full_n(b_V_V_full_n),
    .b_V_V_write(compute_a_b208_U0_b_V_V_write)
);

boxfilter203209 boxfilter203209_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxfilter203209_U0_ap_start),
    .ap_done(boxfilter203209_U0_ap_done),
    .ap_continue(boxfilter203209_U0_ap_continue),
    .ap_idle(boxfilter203209_U0_ap_idle),
    .ap_ready(boxfilter203209_U0_ap_ready),
    .a_V_V_dout(a_V_V_dout),
    .a_V_V_empty_n(a_V_V_empty_n),
    .a_V_V_read(boxfilter203209_U0_a_V_V_read),
    .mean_A_V_V_din(boxfilter203209_U0_mean_A_V_V_din),
    .mean_A_V_V_full_n(mean_A_V_V_full_n),
    .mean_A_V_V_write(boxfilter203209_U0_mean_A_V_V_write)
);

boxfilter210 boxfilter210_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxfilter210_U0_ap_start),
    .ap_done(boxfilter210_U0_ap_done),
    .ap_continue(boxfilter210_U0_ap_continue),
    .ap_idle(boxfilter210_U0_ap_idle),
    .ap_ready(boxfilter210_U0_ap_ready),
    .b_V_V_dout(b_V_V_dout),
    .b_V_V_empty_n(b_V_V_empty_n),
    .b_V_V_read(boxfilter210_U0_b_V_V_read),
    .mean_B_V_V_din(boxfilter210_U0_mean_B_V_V_din),
    .mean_B_V_V_full_n(mean_B_V_V_full_n),
    .mean_B_V_V_write(boxfilter210_U0_mean_B_V_V_write)
);

compute_I_enhanced21 compute_I_enhanced21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_I_enhanced21_U0_ap_start),
    .ap_done(compute_I_enhanced21_U0_ap_done),
    .ap_continue(compute_I_enhanced21_U0_ap_continue),
    .ap_idle(compute_I_enhanced21_U0_ap_idle),
    .ap_ready(compute_I_enhanced21_U0_ap_ready),
    .I_enhanced_data_stream_V_din(compute_I_enhanced21_U0_I_enhanced_data_stream_V_din),
    .I_enhanced_data_stream_V_full_n(I_enhanced_data_stream_V_full_n),
    .I_enhanced_data_stream_V_write(compute_I_enhanced21_U0_I_enhanced_data_stream_V_write),
    .mean_A_V_V_dout(mean_A_V_V_dout),
    .mean_A_V_V_empty_n(mean_A_V_V_empty_n),
    .mean_A_V_V_read(compute_I_enhanced21_U0_mean_A_V_V_read),
    .mean_B_V_V_dout(mean_B_V_V_dout),
    .mean_B_V_V_empty_n(mean_B_V_V_empty_n),
    .mean_B_V_V_read(compute_I_enhanced21_U0_mean_B_V_V_read),
    .N_COPY_V_V_dout(N_COPY_V_V_dout),
    .N_COPY_V_V_empty_n(N_COPY_V_V_empty_n),
    .N_COPY_V_V_read(compute_I_enhanced21_U0_N_COPY_V_V_read),
    .I_COPY_V_V_dout(I_COPY_V_V_dout),
    .I_COPY_V_V_empty_n(I_COPY_V_V_empty_n),
    .I_COPY_V_V_read(compute_I_enhanced21_U0_I_COPY_V_V_read)
);

fifo_w32_d1_A N_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxfilter200205_U0_N_V_V_din),
    .if_full_n(N_V_V_full_n),
    .if_write(boxfilter200205_U0_N_V_V_write),
    .if_dout(N_V_V_dout),
    .if_empty_n(N_V_V_empty_n),
    .if_read(compute_a_b208_U0_N_V_V_read)
);

fifo_w32_d1_A mean_I_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxfilter201206_U0_mean_I_V_V_din),
    .if_full_n(mean_I_V_V_full_n),
    .if_write(boxfilter201206_U0_mean_I_V_V_write),
    .if_dout(mean_I_V_V_dout),
    .if_empty_n(mean_I_V_V_empty_n),
    .if_read(compute_a_b208_U0_mean_I_V_V_read)
);

fifo_w32_d1_A mean_II_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxfilter202207_U0_mean_II_V_V_din),
    .if_full_n(mean_II_V_V_full_n),
    .if_write(boxfilter202207_U0_mean_II_V_V_write),
    .if_dout(mean_II_V_V_dout),
    .if_empty_n(mean_II_V_V_empty_n),
    .if_read(compute_a_b208_U0_mean_II_V_V_read)
);

fifo_w32_d1_A N_COPY_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_a_b208_U0_N_COPY_V_V_din),
    .if_full_n(N_COPY_V_V_full_n),
    .if_write(compute_a_b208_U0_N_COPY_V_V_write),
    .if_dout(N_COPY_V_V_dout),
    .if_empty_n(N_COPY_V_V_empty_n),
    .if_read(compute_I_enhanced21_U0_N_COPY_V_V_read)
);

fifo_w32_d1_A a_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_a_b208_U0_a_V_V_din),
    .if_full_n(a_V_V_full_n),
    .if_write(compute_a_b208_U0_a_V_V_write),
    .if_dout(a_V_V_dout),
    .if_empty_n(a_V_V_empty_n),
    .if_read(boxfilter203209_U0_a_V_V_read)
);

fifo_w32_d1_A b_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_a_b208_U0_b_V_V_din),
    .if_full_n(b_V_V_full_n),
    .if_write(compute_a_b208_U0_b_V_V_write),
    .if_dout(b_V_V_dout),
    .if_empty_n(b_V_V_empty_n),
    .if_read(boxfilter210_U0_b_V_V_read)
);

fifo_w32_d1_A mean_A_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxfilter203209_U0_mean_A_V_V_din),
    .if_full_n(mean_A_V_V_full_n),
    .if_write(boxfilter203209_U0_mean_A_V_V_write),
    .if_dout(mean_A_V_V_dout),
    .if_empty_n(mean_A_V_V_empty_n),
    .if_read(compute_I_enhanced21_U0_mean_A_V_V_read)
);

fifo_w32_d1_A mean_B_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxfilter210_U0_mean_B_V_V_din),
    .if_full_n(mean_B_V_V_full_n),
    .if_write(boxfilter210_U0_mean_B_V_V_write),
    .if_dout(mean_B_V_V_dout),
    .if_empty_n(mean_B_V_V_empty_n),
    .if_read(compute_I_enhanced21_U0_mean_B_V_V_read)
);

start_for_computecUB start_for_computecUB_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_a_b208_U0_din),
    .if_full_n(start_for_compute_a_b208_U0_full_n),
    .if_write(boxfilter200205_U0_start_write),
    .if_dout(start_for_compute_a_b208_U0_dout),
    .if_empty_n(start_for_compute_a_b208_U0_empty_n),
    .if_read(compute_a_b208_U0_ap_ready)
);

start_for_boxfiltcVB start_for_boxfiltcVB_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_boxfilter203209_U0_din),
    .if_full_n(start_for_boxfilter203209_U0_full_n),
    .if_write(compute_a_b208_U0_start_write),
    .if_dout(start_for_boxfilter203209_U0_dout),
    .if_empty_n(start_for_boxfilter203209_U0_empty_n),
    .if_read(boxfilter203209_U0_ap_ready)
);

start_for_boxfiltcWB start_for_boxfiltcWB_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_boxfilter210_U0_din),
    .if_full_n(start_for_boxfilter210_U0_full_n),
    .if_write(compute_a_b208_U0_start_write),
    .if_dout(start_for_boxfilter210_U0_dout),
    .if_empty_n(start_for_boxfilter210_U0_empty_n),
    .if_read(boxfilter210_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_boxfilter200205_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_boxfilter200205_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_boxfilter200205_U0_ap_ready <= ap_sync_boxfilter200205_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_boxfilter201206_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_boxfilter201206_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_boxfilter201206_U0_ap_ready <= ap_sync_boxfilter201206_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_boxfilter202207_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_boxfilter202207_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_boxfilter202207_U0_ap_ready <= ap_sync_boxfilter202207_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= ap_sync_compute_I_enhanced21_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((boxfilter200205_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        boxfilter200205_U0_ap_ready_count <= (boxfilter200205_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (boxfilter200205_U0_ap_ready == 1'b1))) begin
        boxfilter200205_U0_ap_ready_count <= (boxfilter200205_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((boxfilter201206_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        boxfilter201206_U0_ap_ready_count <= (boxfilter201206_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (boxfilter201206_U0_ap_ready == 1'b1))) begin
        boxfilter201206_U0_ap_ready_count <= (boxfilter201206_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((boxfilter202207_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        boxfilter202207_U0_ap_ready_count <= (boxfilter202207_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (boxfilter202207_U0_ap_ready == 1'b1))) begin
        boxfilter202207_U0_ap_ready_count <= (boxfilter202207_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((compute_I_enhanced21_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        compute_I_enhanced21_U0_ap_ready_count <= (compute_I_enhanced21_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (compute_I_enhanced21_U0_ap_ready == 1'b1))) begin
        compute_I_enhanced21_U0_ap_ready_count <= (compute_I_enhanced21_U0_ap_ready_count + 2'd1);
    end
end

assign I_2_V_V_read = boxfilter202207_U0_I_2_V_V_read;

assign I_COPY_V_V_read = compute_I_enhanced21_U0_I_COPY_V_V_read;

assign I_V_V_read = boxfilter201206_U0_I_V_V_read;

assign I_enhanced_data_stream_V_din = compute_I_enhanced21_U0_I_enhanced_data_stream_V_din;

assign I_enhanced_data_stream_V_write = compute_I_enhanced21_U0_I_enhanced_data_stream_V_write;

assign ONES_V_V_read = boxfilter200205_U0_ONES_V_V_read;

assign ap_done = compute_I_enhanced21_U0_ap_done;

assign ap_idle = (compute_a_b208_U0_ap_idle & compute_I_enhanced21_U0_ap_idle & boxfilter210_U0_ap_idle & boxfilter203209_U0_ap_idle & boxfilter202207_U0_ap_idle & boxfilter201206_U0_ap_idle & boxfilter200205_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_boxfilter200205_U0_ap_ready = (boxfilter200205_U0_ap_ready | ap_sync_reg_boxfilter200205_U0_ap_ready);

assign ap_sync_boxfilter201206_U0_ap_ready = (boxfilter201206_U0_ap_ready | ap_sync_reg_boxfilter201206_U0_ap_ready);

assign ap_sync_boxfilter202207_U0_ap_ready = (boxfilter202207_U0_ap_ready | ap_sync_reg_boxfilter202207_U0_ap_ready);

assign ap_sync_compute_I_enhanced21_U0_ap_ready = (compute_I_enhanced21_U0_ap_ready | ap_sync_reg_compute_I_enhanced21_U0_ap_ready);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = compute_I_enhanced21_U0_ap_done;

assign ap_sync_ready = (ap_sync_compute_I_enhanced21_U0_ap_ready & ap_sync_boxfilter202207_U0_ap_ready & ap_sync_boxfilter201206_U0_ap_ready & ap_sync_boxfilter200205_U0_ap_ready);

assign boxfilter200205_U0_ap_continue = 1'b1;

assign boxfilter200205_U0_ap_start = ((ap_sync_reg_boxfilter200205_U0_ap_ready ^ 1'b1) & ap_start);

assign boxfilter201206_U0_ap_continue = 1'b1;

assign boxfilter201206_U0_ap_start = ((ap_sync_reg_boxfilter201206_U0_ap_ready ^ 1'b1) & ap_start);

assign boxfilter201206_U0_start_full_n = 1'b1;

assign boxfilter201206_U0_start_write = 1'b0;

assign boxfilter202207_U0_ap_continue = 1'b1;

assign boxfilter202207_U0_ap_start = ((ap_sync_reg_boxfilter202207_U0_ap_ready ^ 1'b1) & ap_start);

assign boxfilter202207_U0_start_full_n = 1'b1;

assign boxfilter202207_U0_start_write = 1'b0;

assign boxfilter203209_U0_ap_continue = 1'b1;

assign boxfilter203209_U0_ap_start = start_for_boxfilter203209_U0_empty_n;

assign boxfilter203209_U0_start_full_n = 1'b1;

assign boxfilter203209_U0_start_write = 1'b0;

assign boxfilter210_U0_ap_continue = 1'b1;

assign boxfilter210_U0_ap_start = start_for_boxfilter210_U0_empty_n;

assign boxfilter210_U0_start_full_n = 1'b1;

assign boxfilter210_U0_start_write = 1'b0;

assign compute_I_enhanced21_U0_ap_continue = ap_continue;

assign compute_I_enhanced21_U0_ap_start = ((ap_sync_reg_compute_I_enhanced21_U0_ap_ready ^ 1'b1) & ap_start);

assign compute_I_enhanced21_U0_start_full_n = 1'b1;

assign compute_I_enhanced21_U0_start_write = 1'b0;

assign compute_a_b208_U0_ap_continue = 1'b1;

assign compute_a_b208_U0_ap_start = start_for_compute_a_b208_U0_empty_n;

assign compute_a_b208_U0_start_full_n = (start_for_boxfilter210_U0_full_n & start_for_boxfilter203209_U0_full_n);

assign start_for_boxfilter203209_U0_din = 1'b1;

assign start_for_boxfilter210_U0_din = 1'b1;

assign start_for_compute_a_b208_U0_din = 1'b1;

endmodule //guidedfilter204
