-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity guidedfilter204 is
port (
    I_enhanced_data_stream_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    I_enhanced_data_stream_V_full_n : IN STD_LOGIC;
    I_enhanced_data_stream_V_write : OUT STD_LOGIC;
    ONES_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ONES_V_V_empty_n : IN STD_LOGIC;
    ONES_V_V_read : OUT STD_LOGIC;
    I_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    I_V_V_empty_n : IN STD_LOGIC;
    I_V_V_read : OUT STD_LOGIC;
    I_2_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    I_2_V_V_empty_n : IN STD_LOGIC;
    I_2_V_V_read : OUT STD_LOGIC;
    I_COPY_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    I_COPY_V_V_empty_n : IN STD_LOGIC;
    I_COPY_V_V_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of guidedfilter204 is 
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal boxfilter200205_U0_ap_start : STD_LOGIC;
    signal boxfilter200205_U0_ap_done : STD_LOGIC;
    signal boxfilter200205_U0_ap_continue : STD_LOGIC;
    signal boxfilter200205_U0_ap_idle : STD_LOGIC;
    signal boxfilter200205_U0_ap_ready : STD_LOGIC;
    signal boxfilter200205_U0_start_out : STD_LOGIC;
    signal boxfilter200205_U0_start_write : STD_LOGIC;
    signal boxfilter200205_U0_ONES_V_V_read : STD_LOGIC;
    signal boxfilter200205_U0_N_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal boxfilter200205_U0_N_V_V_write : STD_LOGIC;
    signal boxfilter201206_U0_ap_start : STD_LOGIC;
    signal boxfilter201206_U0_ap_done : STD_LOGIC;
    signal boxfilter201206_U0_ap_continue : STD_LOGIC;
    signal boxfilter201206_U0_ap_idle : STD_LOGIC;
    signal boxfilter201206_U0_ap_ready : STD_LOGIC;
    signal boxfilter201206_U0_I_V_V_read : STD_LOGIC;
    signal boxfilter201206_U0_mean_I_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal boxfilter201206_U0_mean_I_V_V_write : STD_LOGIC;
    signal boxfilter202207_U0_ap_start : STD_LOGIC;
    signal boxfilter202207_U0_ap_done : STD_LOGIC;
    signal boxfilter202207_U0_ap_continue : STD_LOGIC;
    signal boxfilter202207_U0_ap_idle : STD_LOGIC;
    signal boxfilter202207_U0_ap_ready : STD_LOGIC;
    signal boxfilter202207_U0_I_2_V_V_read : STD_LOGIC;
    signal boxfilter202207_U0_mean_II_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal boxfilter202207_U0_mean_II_V_V_write : STD_LOGIC;
    signal compute_a_b208_U0_ap_start : STD_LOGIC;
    signal compute_a_b208_U0_start_full_n : STD_LOGIC;
    signal compute_a_b208_U0_ap_done : STD_LOGIC;
    signal compute_a_b208_U0_ap_continue : STD_LOGIC;
    signal compute_a_b208_U0_ap_idle : STD_LOGIC;
    signal compute_a_b208_U0_ap_ready : STD_LOGIC;
    signal compute_a_b208_U0_start_out : STD_LOGIC;
    signal compute_a_b208_U0_start_write : STD_LOGIC;
    signal compute_a_b208_U0_N_V_V_read : STD_LOGIC;
    signal compute_a_b208_U0_N_COPY_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_a_b208_U0_N_COPY_V_V_write : STD_LOGIC;
    signal compute_a_b208_U0_mean_I_V_V_read : STD_LOGIC;
    signal compute_a_b208_U0_mean_II_V_V_read : STD_LOGIC;
    signal compute_a_b208_U0_a_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_a_b208_U0_a_V_V_write : STD_LOGIC;
    signal compute_a_b208_U0_b_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_a_b208_U0_b_V_V_write : STD_LOGIC;
    signal boxfilter203209_U0_ap_start : STD_LOGIC;
    signal boxfilter203209_U0_ap_done : STD_LOGIC;
    signal boxfilter203209_U0_ap_continue : STD_LOGIC;
    signal boxfilter203209_U0_ap_idle : STD_LOGIC;
    signal boxfilter203209_U0_ap_ready : STD_LOGIC;
    signal boxfilter203209_U0_a_V_V_read : STD_LOGIC;
    signal boxfilter203209_U0_mean_A_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal boxfilter203209_U0_mean_A_V_V_write : STD_LOGIC;
    signal boxfilter210_U0_ap_start : STD_LOGIC;
    signal boxfilter210_U0_ap_done : STD_LOGIC;
    signal boxfilter210_U0_ap_continue : STD_LOGIC;
    signal boxfilter210_U0_ap_idle : STD_LOGIC;
    signal boxfilter210_U0_ap_ready : STD_LOGIC;
    signal boxfilter210_U0_b_V_V_read : STD_LOGIC;
    signal boxfilter210_U0_mean_B_V_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal boxfilter210_U0_mean_B_V_V_write : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_start : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_done : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_continue : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_idle : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_ready : STD_LOGIC;
    signal compute_I_enhanced21_U0_I_enhanced_data_stream_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal compute_I_enhanced21_U0_I_enhanced_data_stream_V_write : STD_LOGIC;
    signal compute_I_enhanced21_U0_mean_A_V_V_read : STD_LOGIC;
    signal compute_I_enhanced21_U0_mean_B_V_V_read : STD_LOGIC;
    signal compute_I_enhanced21_U0_N_COPY_V_V_read : STD_LOGIC;
    signal compute_I_enhanced21_U0_I_COPY_V_V_read : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal N_V_V_full_n : STD_LOGIC;
    signal N_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal N_V_V_empty_n : STD_LOGIC;
    signal mean_I_V_V_full_n : STD_LOGIC;
    signal mean_I_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal mean_I_V_V_empty_n : STD_LOGIC;
    signal mean_II_V_V_full_n : STD_LOGIC;
    signal mean_II_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal mean_II_V_V_empty_n : STD_LOGIC;
    signal N_COPY_V_V_full_n : STD_LOGIC;
    signal N_COPY_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal N_COPY_V_V_empty_n : STD_LOGIC;
    signal a_V_V_full_n : STD_LOGIC;
    signal a_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal a_V_V_empty_n : STD_LOGIC;
    signal b_V_V_full_n : STD_LOGIC;
    signal b_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal b_V_V_empty_n : STD_LOGIC;
    signal mean_A_V_V_full_n : STD_LOGIC;
    signal mean_A_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal mean_A_V_V_empty_n : STD_LOGIC;
    signal mean_B_V_V_full_n : STD_LOGIC;
    signal mean_B_V_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal mean_B_V_V_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_boxfilter200205_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_boxfilter200205_U0_ap_ready : STD_LOGIC;
    signal boxfilter200205_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_boxfilter201206_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_boxfilter201206_U0_ap_ready : STD_LOGIC;
    signal boxfilter201206_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_boxfilter202207_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_boxfilter202207_U0_ap_ready : STD_LOGIC;
    signal boxfilter202207_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_compute_I_enhanced21_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_compute_I_enhanced21_U0_ap_ready : STD_LOGIC;
    signal compute_I_enhanced21_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal start_for_compute_a_b208_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_a_b208_U0_full_n : STD_LOGIC;
    signal start_for_compute_a_b208_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_compute_a_b208_U0_empty_n : STD_LOGIC;
    signal boxfilter201206_U0_start_full_n : STD_LOGIC;
    signal boxfilter201206_U0_start_write : STD_LOGIC;
    signal boxfilter202207_U0_start_full_n : STD_LOGIC;
    signal boxfilter202207_U0_start_write : STD_LOGIC;
    signal start_for_boxfilter203209_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_boxfilter203209_U0_full_n : STD_LOGIC;
    signal start_for_boxfilter203209_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_boxfilter203209_U0_empty_n : STD_LOGIC;
    signal start_for_boxfilter210_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_boxfilter210_U0_full_n : STD_LOGIC;
    signal start_for_boxfilter210_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_boxfilter210_U0_empty_n : STD_LOGIC;
    signal boxfilter203209_U0_start_full_n : STD_LOGIC;
    signal boxfilter203209_U0_start_write : STD_LOGIC;
    signal boxfilter210_U0_start_full_n : STD_LOGIC;
    signal boxfilter210_U0_start_write : STD_LOGIC;
    signal compute_I_enhanced21_U0_start_full_n : STD_LOGIC;
    signal compute_I_enhanced21_U0_start_write : STD_LOGIC;

    component boxfilter200205 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        ONES_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ONES_V_V_empty_n : IN STD_LOGIC;
        ONES_V_V_read : OUT STD_LOGIC;
        N_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        N_V_V_full_n : IN STD_LOGIC;
        N_V_V_write : OUT STD_LOGIC );
    end component;


    component boxfilter201206 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        I_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        I_V_V_empty_n : IN STD_LOGIC;
        I_V_V_read : OUT STD_LOGIC;
        mean_I_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mean_I_V_V_full_n : IN STD_LOGIC;
        mean_I_V_V_write : OUT STD_LOGIC );
    end component;


    component boxfilter202207 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        I_2_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        I_2_V_V_empty_n : IN STD_LOGIC;
        I_2_V_V_read : OUT STD_LOGIC;
        mean_II_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mean_II_V_V_full_n : IN STD_LOGIC;
        mean_II_V_V_write : OUT STD_LOGIC );
    end component;


    component compute_a_b208 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        N_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        N_V_V_empty_n : IN STD_LOGIC;
        N_V_V_read : OUT STD_LOGIC;
        N_COPY_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        N_COPY_V_V_full_n : IN STD_LOGIC;
        N_COPY_V_V_write : OUT STD_LOGIC;
        mean_I_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        mean_I_V_V_empty_n : IN STD_LOGIC;
        mean_I_V_V_read : OUT STD_LOGIC;
        mean_II_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        mean_II_V_V_empty_n : IN STD_LOGIC;
        mean_II_V_V_read : OUT STD_LOGIC;
        a_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_V_V_full_n : IN STD_LOGIC;
        a_V_V_write : OUT STD_LOGIC;
        b_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_V_V_full_n : IN STD_LOGIC;
        b_V_V_write : OUT STD_LOGIC );
    end component;


    component boxfilter203209 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        a_V_V_empty_n : IN STD_LOGIC;
        a_V_V_read : OUT STD_LOGIC;
        mean_A_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mean_A_V_V_full_n : IN STD_LOGIC;
        mean_A_V_V_write : OUT STD_LOGIC );
    end component;


    component boxfilter210 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        b_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        b_V_V_empty_n : IN STD_LOGIC;
        b_V_V_read : OUT STD_LOGIC;
        mean_B_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        mean_B_V_V_full_n : IN STD_LOGIC;
        mean_B_V_V_write : OUT STD_LOGIC );
    end component;


    component compute_I_enhanced21 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        I_enhanced_data_stream_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        I_enhanced_data_stream_V_full_n : IN STD_LOGIC;
        I_enhanced_data_stream_V_write : OUT STD_LOGIC;
        mean_A_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        mean_A_V_V_empty_n : IN STD_LOGIC;
        mean_A_V_V_read : OUT STD_LOGIC;
        mean_B_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        mean_B_V_V_empty_n : IN STD_LOGIC;
        mean_B_V_V_read : OUT STD_LOGIC;
        N_COPY_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        N_COPY_V_V_empty_n : IN STD_LOGIC;
        N_COPY_V_V_read : OUT STD_LOGIC;
        I_COPY_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        I_COPY_V_V_empty_n : IN STD_LOGIC;
        I_COPY_V_V_read : OUT STD_LOGIC );
    end component;


    component fifo_w32_d1_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_computecUB IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_boxfiltcVB IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_boxfiltcWB IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    boxfilter200205_U0 : component boxfilter200205
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => boxfilter200205_U0_ap_start,
        start_full_n => start_for_compute_a_b208_U0_full_n,
        ap_done => boxfilter200205_U0_ap_done,
        ap_continue => boxfilter200205_U0_ap_continue,
        ap_idle => boxfilter200205_U0_ap_idle,
        ap_ready => boxfilter200205_U0_ap_ready,
        start_out => boxfilter200205_U0_start_out,
        start_write => boxfilter200205_U0_start_write,
        ONES_V_V_dout => ONES_V_V_dout,
        ONES_V_V_empty_n => ONES_V_V_empty_n,
        ONES_V_V_read => boxfilter200205_U0_ONES_V_V_read,
        N_V_V_din => boxfilter200205_U0_N_V_V_din,
        N_V_V_full_n => N_V_V_full_n,
        N_V_V_write => boxfilter200205_U0_N_V_V_write);

    boxfilter201206_U0 : component boxfilter201206
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => boxfilter201206_U0_ap_start,
        ap_done => boxfilter201206_U0_ap_done,
        ap_continue => boxfilter201206_U0_ap_continue,
        ap_idle => boxfilter201206_U0_ap_idle,
        ap_ready => boxfilter201206_U0_ap_ready,
        I_V_V_dout => I_V_V_dout,
        I_V_V_empty_n => I_V_V_empty_n,
        I_V_V_read => boxfilter201206_U0_I_V_V_read,
        mean_I_V_V_din => boxfilter201206_U0_mean_I_V_V_din,
        mean_I_V_V_full_n => mean_I_V_V_full_n,
        mean_I_V_V_write => boxfilter201206_U0_mean_I_V_V_write);

    boxfilter202207_U0 : component boxfilter202207
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => boxfilter202207_U0_ap_start,
        ap_done => boxfilter202207_U0_ap_done,
        ap_continue => boxfilter202207_U0_ap_continue,
        ap_idle => boxfilter202207_U0_ap_idle,
        ap_ready => boxfilter202207_U0_ap_ready,
        I_2_V_V_dout => I_2_V_V_dout,
        I_2_V_V_empty_n => I_2_V_V_empty_n,
        I_2_V_V_read => boxfilter202207_U0_I_2_V_V_read,
        mean_II_V_V_din => boxfilter202207_U0_mean_II_V_V_din,
        mean_II_V_V_full_n => mean_II_V_V_full_n,
        mean_II_V_V_write => boxfilter202207_U0_mean_II_V_V_write);

    compute_a_b208_U0 : component compute_a_b208
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_a_b208_U0_ap_start,
        start_full_n => compute_a_b208_U0_start_full_n,
        ap_done => compute_a_b208_U0_ap_done,
        ap_continue => compute_a_b208_U0_ap_continue,
        ap_idle => compute_a_b208_U0_ap_idle,
        ap_ready => compute_a_b208_U0_ap_ready,
        start_out => compute_a_b208_U0_start_out,
        start_write => compute_a_b208_U0_start_write,
        N_V_V_dout => N_V_V_dout,
        N_V_V_empty_n => N_V_V_empty_n,
        N_V_V_read => compute_a_b208_U0_N_V_V_read,
        N_COPY_V_V_din => compute_a_b208_U0_N_COPY_V_V_din,
        N_COPY_V_V_full_n => N_COPY_V_V_full_n,
        N_COPY_V_V_write => compute_a_b208_U0_N_COPY_V_V_write,
        mean_I_V_V_dout => mean_I_V_V_dout,
        mean_I_V_V_empty_n => mean_I_V_V_empty_n,
        mean_I_V_V_read => compute_a_b208_U0_mean_I_V_V_read,
        mean_II_V_V_dout => mean_II_V_V_dout,
        mean_II_V_V_empty_n => mean_II_V_V_empty_n,
        mean_II_V_V_read => compute_a_b208_U0_mean_II_V_V_read,
        a_V_V_din => compute_a_b208_U0_a_V_V_din,
        a_V_V_full_n => a_V_V_full_n,
        a_V_V_write => compute_a_b208_U0_a_V_V_write,
        b_V_V_din => compute_a_b208_U0_b_V_V_din,
        b_V_V_full_n => b_V_V_full_n,
        b_V_V_write => compute_a_b208_U0_b_V_V_write);

    boxfilter203209_U0 : component boxfilter203209
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => boxfilter203209_U0_ap_start,
        ap_done => boxfilter203209_U0_ap_done,
        ap_continue => boxfilter203209_U0_ap_continue,
        ap_idle => boxfilter203209_U0_ap_idle,
        ap_ready => boxfilter203209_U0_ap_ready,
        a_V_V_dout => a_V_V_dout,
        a_V_V_empty_n => a_V_V_empty_n,
        a_V_V_read => boxfilter203209_U0_a_V_V_read,
        mean_A_V_V_din => boxfilter203209_U0_mean_A_V_V_din,
        mean_A_V_V_full_n => mean_A_V_V_full_n,
        mean_A_V_V_write => boxfilter203209_U0_mean_A_V_V_write);

    boxfilter210_U0 : component boxfilter210
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => boxfilter210_U0_ap_start,
        ap_done => boxfilter210_U0_ap_done,
        ap_continue => boxfilter210_U0_ap_continue,
        ap_idle => boxfilter210_U0_ap_idle,
        ap_ready => boxfilter210_U0_ap_ready,
        b_V_V_dout => b_V_V_dout,
        b_V_V_empty_n => b_V_V_empty_n,
        b_V_V_read => boxfilter210_U0_b_V_V_read,
        mean_B_V_V_din => boxfilter210_U0_mean_B_V_V_din,
        mean_B_V_V_full_n => mean_B_V_V_full_n,
        mean_B_V_V_write => boxfilter210_U0_mean_B_V_V_write);

    compute_I_enhanced21_U0 : component compute_I_enhanced21
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => compute_I_enhanced21_U0_ap_start,
        ap_done => compute_I_enhanced21_U0_ap_done,
        ap_continue => compute_I_enhanced21_U0_ap_continue,
        ap_idle => compute_I_enhanced21_U0_ap_idle,
        ap_ready => compute_I_enhanced21_U0_ap_ready,
        I_enhanced_data_stream_V_din => compute_I_enhanced21_U0_I_enhanced_data_stream_V_din,
        I_enhanced_data_stream_V_full_n => I_enhanced_data_stream_V_full_n,
        I_enhanced_data_stream_V_write => compute_I_enhanced21_U0_I_enhanced_data_stream_V_write,
        mean_A_V_V_dout => mean_A_V_V_dout,
        mean_A_V_V_empty_n => mean_A_V_V_empty_n,
        mean_A_V_V_read => compute_I_enhanced21_U0_mean_A_V_V_read,
        mean_B_V_V_dout => mean_B_V_V_dout,
        mean_B_V_V_empty_n => mean_B_V_V_empty_n,
        mean_B_V_V_read => compute_I_enhanced21_U0_mean_B_V_V_read,
        N_COPY_V_V_dout => N_COPY_V_V_dout,
        N_COPY_V_V_empty_n => N_COPY_V_V_empty_n,
        N_COPY_V_V_read => compute_I_enhanced21_U0_N_COPY_V_V_read,
        I_COPY_V_V_dout => I_COPY_V_V_dout,
        I_COPY_V_V_empty_n => I_COPY_V_V_empty_n,
        I_COPY_V_V_read => compute_I_enhanced21_U0_I_COPY_V_V_read);

    N_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => boxfilter200205_U0_N_V_V_din,
        if_full_n => N_V_V_full_n,
        if_write => boxfilter200205_U0_N_V_V_write,
        if_dout => N_V_V_dout,
        if_empty_n => N_V_V_empty_n,
        if_read => compute_a_b208_U0_N_V_V_read);

    mean_I_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => boxfilter201206_U0_mean_I_V_V_din,
        if_full_n => mean_I_V_V_full_n,
        if_write => boxfilter201206_U0_mean_I_V_V_write,
        if_dout => mean_I_V_V_dout,
        if_empty_n => mean_I_V_V_empty_n,
        if_read => compute_a_b208_U0_mean_I_V_V_read);

    mean_II_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => boxfilter202207_U0_mean_II_V_V_din,
        if_full_n => mean_II_V_V_full_n,
        if_write => boxfilter202207_U0_mean_II_V_V_write,
        if_dout => mean_II_V_V_dout,
        if_empty_n => mean_II_V_V_empty_n,
        if_read => compute_a_b208_U0_mean_II_V_V_read);

    N_COPY_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_a_b208_U0_N_COPY_V_V_din,
        if_full_n => N_COPY_V_V_full_n,
        if_write => compute_a_b208_U0_N_COPY_V_V_write,
        if_dout => N_COPY_V_V_dout,
        if_empty_n => N_COPY_V_V_empty_n,
        if_read => compute_I_enhanced21_U0_N_COPY_V_V_read);

    a_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_a_b208_U0_a_V_V_din,
        if_full_n => a_V_V_full_n,
        if_write => compute_a_b208_U0_a_V_V_write,
        if_dout => a_V_V_dout,
        if_empty_n => a_V_V_empty_n,
        if_read => boxfilter203209_U0_a_V_V_read);

    b_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => compute_a_b208_U0_b_V_V_din,
        if_full_n => b_V_V_full_n,
        if_write => compute_a_b208_U0_b_V_V_write,
        if_dout => b_V_V_dout,
        if_empty_n => b_V_V_empty_n,
        if_read => boxfilter210_U0_b_V_V_read);

    mean_A_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => boxfilter203209_U0_mean_A_V_V_din,
        if_full_n => mean_A_V_V_full_n,
        if_write => boxfilter203209_U0_mean_A_V_V_write,
        if_dout => mean_A_V_V_dout,
        if_empty_n => mean_A_V_V_empty_n,
        if_read => compute_I_enhanced21_U0_mean_A_V_V_read);

    mean_B_V_V_U : component fifo_w32_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => boxfilter210_U0_mean_B_V_V_din,
        if_full_n => mean_B_V_V_full_n,
        if_write => boxfilter210_U0_mean_B_V_V_write,
        if_dout => mean_B_V_V_dout,
        if_empty_n => mean_B_V_V_empty_n,
        if_read => compute_I_enhanced21_U0_mean_B_V_V_read);

    start_for_computecUB_U : component start_for_computecUB
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_compute_a_b208_U0_din,
        if_full_n => start_for_compute_a_b208_U0_full_n,
        if_write => boxfilter200205_U0_start_write,
        if_dout => start_for_compute_a_b208_U0_dout,
        if_empty_n => start_for_compute_a_b208_U0_empty_n,
        if_read => compute_a_b208_U0_ap_ready);

    start_for_boxfiltcVB_U : component start_for_boxfiltcVB
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_boxfilter203209_U0_din,
        if_full_n => start_for_boxfilter203209_U0_full_n,
        if_write => compute_a_b208_U0_start_write,
        if_dout => start_for_boxfilter203209_U0_dout,
        if_empty_n => start_for_boxfilter203209_U0_empty_n,
        if_read => boxfilter203209_U0_ap_ready);

    start_for_boxfiltcWB_U : component start_for_boxfiltcWB
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_boxfilter210_U0_din,
        if_full_n => start_for_boxfilter210_U0_full_n,
        if_write => compute_a_b208_U0_start_write,
        if_dout => start_for_boxfilter210_U0_dout,
        if_empty_n => start_for_boxfilter210_U0_empty_n,
        if_read => boxfilter210_U0_ap_ready);





    ap_sync_reg_boxfilter200205_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_boxfilter200205_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_boxfilter200205_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_boxfilter200205_U0_ap_ready <= ap_sync_boxfilter200205_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_boxfilter201206_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_boxfilter201206_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_boxfilter201206_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_boxfilter201206_U0_ap_ready <= ap_sync_boxfilter201206_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_boxfilter202207_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_boxfilter202207_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_boxfilter202207_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_boxfilter202207_U0_ap_ready <= ap_sync_boxfilter202207_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_compute_I_enhanced21_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_compute_I_enhanced21_U0_ap_ready <= ap_sync_compute_I_enhanced21_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    boxfilter200205_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((boxfilter200205_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                boxfilter200205_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter200205_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (boxfilter200205_U0_ap_ready = ap_const_logic_1))) then 
                boxfilter200205_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter200205_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    boxfilter201206_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((boxfilter201206_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                boxfilter201206_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter201206_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (boxfilter201206_U0_ap_ready = ap_const_logic_1))) then 
                boxfilter201206_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter201206_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    boxfilter202207_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((boxfilter202207_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                boxfilter202207_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter202207_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (boxfilter202207_U0_ap_ready = ap_const_logic_1))) then 
                boxfilter202207_U0_ap_ready_count <= std_logic_vector(unsigned(boxfilter202207_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    compute_I_enhanced21_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((compute_I_enhanced21_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                compute_I_enhanced21_U0_ap_ready_count <= std_logic_vector(unsigned(compute_I_enhanced21_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (compute_I_enhanced21_U0_ap_ready = ap_const_logic_1))) then 
                compute_I_enhanced21_U0_ap_ready_count <= std_logic_vector(unsigned(compute_I_enhanced21_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    I_2_V_V_read <= boxfilter202207_U0_I_2_V_V_read;
    I_COPY_V_V_read <= compute_I_enhanced21_U0_I_COPY_V_V_read;
    I_V_V_read <= boxfilter201206_U0_I_V_V_read;
    I_enhanced_data_stream_V_din <= compute_I_enhanced21_U0_I_enhanced_data_stream_V_din;
    I_enhanced_data_stream_V_write <= compute_I_enhanced21_U0_I_enhanced_data_stream_V_write;
    ONES_V_V_read <= boxfilter200205_U0_ONES_V_V_read;
    ap_done <= compute_I_enhanced21_U0_ap_done;
    ap_idle <= (compute_a_b208_U0_ap_idle and compute_I_enhanced21_U0_ap_idle and boxfilter210_U0_ap_idle and boxfilter203209_U0_ap_idle and boxfilter202207_U0_ap_idle and boxfilter201206_U0_ap_idle and boxfilter200205_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_boxfilter200205_U0_ap_ready <= (boxfilter200205_U0_ap_ready or ap_sync_reg_boxfilter200205_U0_ap_ready);
    ap_sync_boxfilter201206_U0_ap_ready <= (boxfilter201206_U0_ap_ready or ap_sync_reg_boxfilter201206_U0_ap_ready);
    ap_sync_boxfilter202207_U0_ap_ready <= (boxfilter202207_U0_ap_ready or ap_sync_reg_boxfilter202207_U0_ap_ready);
    ap_sync_compute_I_enhanced21_U0_ap_ready <= (compute_I_enhanced21_U0_ap_ready or ap_sync_reg_compute_I_enhanced21_U0_ap_ready);
    ap_sync_continue <= ap_continue;
    ap_sync_done <= compute_I_enhanced21_U0_ap_done;
    ap_sync_ready <= (ap_sync_compute_I_enhanced21_U0_ap_ready and ap_sync_boxfilter202207_U0_ap_ready and ap_sync_boxfilter201206_U0_ap_ready and ap_sync_boxfilter200205_U0_ap_ready);
    boxfilter200205_U0_ap_continue <= ap_const_logic_1;
    boxfilter200205_U0_ap_start <= ((ap_sync_reg_boxfilter200205_U0_ap_ready xor ap_const_logic_1) and ap_start);
    boxfilter201206_U0_ap_continue <= ap_const_logic_1;
    boxfilter201206_U0_ap_start <= ((ap_sync_reg_boxfilter201206_U0_ap_ready xor ap_const_logic_1) and ap_start);
    boxfilter201206_U0_start_full_n <= ap_const_logic_1;
    boxfilter201206_U0_start_write <= ap_const_logic_0;
    boxfilter202207_U0_ap_continue <= ap_const_logic_1;
    boxfilter202207_U0_ap_start <= ((ap_sync_reg_boxfilter202207_U0_ap_ready xor ap_const_logic_1) and ap_start);
    boxfilter202207_U0_start_full_n <= ap_const_logic_1;
    boxfilter202207_U0_start_write <= ap_const_logic_0;
    boxfilter203209_U0_ap_continue <= ap_const_logic_1;
    boxfilter203209_U0_ap_start <= start_for_boxfilter203209_U0_empty_n;
    boxfilter203209_U0_start_full_n <= ap_const_logic_1;
    boxfilter203209_U0_start_write <= ap_const_logic_0;
    boxfilter210_U0_ap_continue <= ap_const_logic_1;
    boxfilter210_U0_ap_start <= start_for_boxfilter210_U0_empty_n;
    boxfilter210_U0_start_full_n <= ap_const_logic_1;
    boxfilter210_U0_start_write <= ap_const_logic_0;
    compute_I_enhanced21_U0_ap_continue <= ap_continue;
    compute_I_enhanced21_U0_ap_start <= ((ap_sync_reg_compute_I_enhanced21_U0_ap_ready xor ap_const_logic_1) and ap_start);
    compute_I_enhanced21_U0_start_full_n <= ap_const_logic_1;
    compute_I_enhanced21_U0_start_write <= ap_const_logic_0;
    compute_a_b208_U0_ap_continue <= ap_const_logic_1;
    compute_a_b208_U0_ap_start <= start_for_compute_a_b208_U0_empty_n;
    compute_a_b208_U0_start_full_n <= (start_for_boxfilter210_U0_full_n and start_for_boxfilter203209_U0_full_n);
    start_for_boxfilter203209_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_boxfilter210_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_compute_a_b208_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
