// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _adaptive_threshold_HH_
#define _adaptive_threshold_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct adaptive_threshold : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<16> > IN_data_stream_V_dout;
    sc_in< sc_logic > IN_data_stream_V_empty_n;
    sc_out< sc_logic > IN_data_stream_V_read;
    sc_in< sc_lv<16> > IN1_data_stream_V_dout;
    sc_in< sc_logic > IN1_data_stream_V_empty_n;
    sc_out< sc_logic > IN1_data_stream_V_read;
    sc_out< sc_lv<32> > help_V_V_din;
    sc_in< sc_logic > help_V_V_full_n;
    sc_out< sc_logic > help_V_V_write;


    // Module declarations
    adaptive_threshold(sc_module_name name);
    SC_HAS_PROCESS(adaptive_threshold);

    ~adaptive_threshold();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > IN_data_stream_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln887_reg_305;
    sc_signal< sc_logic > IN1_data_stream_V_blk_n;
    sc_signal< sc_logic > help_V_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > icmp_ln887_reg_305_pp0_iter1_reg;
    sc_signal< sc_lv<17> > indvar_flatten_reg_103;
    sc_signal< sc_lv<1> > icmp_ln887_fu_114_p2;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<17> > add_ln887_fu_120_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_39_fu_224_p3;
    sc_signal< sc_lv<1> > tmp_39_reg_314;
    sc_signal< sc_lv<29> > tmp_40_fu_232_p4;
    sc_signal< sc_lv<29> > tmp_40_reg_319;
    sc_signal< sc_lv<29> > sub_ln703_fu_260_p2;
    sc_signal< sc_lv<29> > sub_ln703_reg_324;
    sc_signal< sc_lv<23> > add_ln703_fu_266_p2;
    sc_signal< sc_lv<23> > add_ln703_reg_329;
    sc_signal< bool > ap_block_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<32> > pix1_V_fu_134_p3;
    sc_signal< sc_lv<32> > mul_ln1148_fu_146_p1;
    sc_signal< sc_lv<65> > mul_ln1148_fu_146_p2;
    sc_signal< sc_lv<65> > sub_ln1148_fu_152_p2;
    sc_signal< sc_lv<1> > tmp_fu_158_p3;
    sc_signal< sc_lv<23> > tmp_37_fu_166_p4;
    sc_signal< sc_lv<23> > tmp_38_fu_176_p4;
    sc_signal< sc_lv<23> > select_ln1148_fu_186_p3;
    sc_signal< sc_lv<23> > sub_ln203_fu_194_p2;
    sc_signal< sc_lv<32> > pix_V_fu_126_p3;
    sc_signal< sc_lv<32> > mul_fu_212_p1;
    sc_signal< sc_lv<65> > mul_fu_212_p2;
    sc_signal< sc_lv<65> > neg_mul_fu_218_p2;
    sc_signal< sc_lv<29> > tmp_41_fu_242_p4;
    sc_signal< sc_lv<29> > p_v10_v_fu_252_p3;
    sc_signal< sc_lv<23> > select_ln1148_1_fu_200_p3;
    sc_signal< sc_lv<29> > empty_284_fu_272_p3;
    sc_signal< sc_lv<29> > sext_ln703_fu_277_p1;
    sc_signal< sc_lv<29> > pix2_V_fu_280_p2;
    sc_signal< sc_lv<1> > icmp_ln1497_fu_286_p2;
    sc_signal< sc_lv<17> > pix2_V_2_fu_292_p3;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<17> ap_const_lv17_1FA40;
    static const sc_lv<17> ap_const_lv17_1;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<65> ap_const_lv65_10624DD30;
    static const sc_lv<65> ap_const_lv65_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<65> ap_const_lv65_19999999A;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<29> ap_const_lv29_0;
    static const sc_lv<23> ap_const_lv23_7ECCCD;
    static const sc_lv<29> ap_const_lv29_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_IN1_data_stream_V_blk_n();
    void thread_IN1_data_stream_V_read();
    void thread_IN_data_stream_V_blk_n();
    void thread_IN_data_stream_V_read();
    void thread_add_ln703_fu_266_p2();
    void thread_add_ln887_fu_120_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_empty_284_fu_272_p3();
    void thread_help_V_V_blk_n();
    void thread_help_V_V_din();
    void thread_help_V_V_write();
    void thread_icmp_ln1497_fu_286_p2();
    void thread_icmp_ln887_fu_114_p2();
    void thread_internal_ap_ready();
    void thread_mul_fu_212_p1();
    void thread_mul_fu_212_p2();
    void thread_mul_ln1148_fu_146_p1();
    void thread_mul_ln1148_fu_146_p2();
    void thread_neg_mul_fu_218_p2();
    void thread_p_v10_v_fu_252_p3();
    void thread_pix1_V_fu_134_p3();
    void thread_pix2_V_2_fu_292_p3();
    void thread_pix2_V_fu_280_p2();
    void thread_pix_V_fu_126_p3();
    void thread_real_start();
    void thread_select_ln1148_1_fu_200_p3();
    void thread_select_ln1148_fu_186_p3();
    void thread_sext_ln703_fu_277_p1();
    void thread_start_out();
    void thread_start_write();
    void thread_sub_ln1148_fu_152_p2();
    void thread_sub_ln203_fu_194_p2();
    void thread_sub_ln703_fu_260_p2();
    void thread_tmp_37_fu_166_p4();
    void thread_tmp_38_fu_176_p4();
    void thread_tmp_39_fu_224_p3();
    void thread_tmp_40_fu_232_p4();
    void thread_tmp_41_fu_242_p4();
    void thread_tmp_fu_158_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
