// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _guidedfilter204_HH_
#define _guidedfilter204_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "boxfilter200205.h"
#include "boxfilter201206.h"
#include "boxfilter202207.h"
#include "compute_a_b208.h"
#include "boxfilter203209.h"
#include "boxfilter210.h"
#include "compute_I_enhanced21.h"
#include "fifo_w32_d1_A.h"
#include "start_for_computecUB.h"
#include "start_for_boxfiltcVB.h"
#include "start_for_boxfiltcWB.h"

namespace ap_rtl {

struct guidedfilter204 : public sc_module {
    // Port declarations 22
    sc_out< sc_lv<16> > I_enhanced_data_stream_V_din;
    sc_in< sc_logic > I_enhanced_data_stream_V_full_n;
    sc_out< sc_logic > I_enhanced_data_stream_V_write;
    sc_in< sc_lv<32> > ONES_V_V_dout;
    sc_in< sc_logic > ONES_V_V_empty_n;
    sc_out< sc_logic > ONES_V_V_read;
    sc_in< sc_lv<32> > I_V_V_dout;
    sc_in< sc_logic > I_V_V_empty_n;
    sc_out< sc_logic > I_V_V_read;
    sc_in< sc_lv<32> > I_2_V_V_dout;
    sc_in< sc_logic > I_2_V_V_empty_n;
    sc_out< sc_logic > I_2_V_V_read;
    sc_in< sc_lv<32> > I_COPY_V_V_dout;
    sc_in< sc_logic > I_COPY_V_V_empty_n;
    sc_out< sc_logic > I_COPY_V_V_read;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    guidedfilter204(sc_module_name name);
    SC_HAS_PROCESS(guidedfilter204);

    ~guidedfilter204();

    sc_trace_file* mVcdFile;

    boxfilter200205* boxfilter200205_U0;
    boxfilter201206* boxfilter201206_U0;
    boxfilter202207* boxfilter202207_U0;
    compute_a_b208* compute_a_b208_U0;
    boxfilter203209* boxfilter203209_U0;
    boxfilter210* boxfilter210_U0;
    compute_I_enhanced21* compute_I_enhanced21_U0;
    fifo_w32_d1_A* N_V_V_U;
    fifo_w32_d1_A* mean_I_V_V_U;
    fifo_w32_d1_A* mean_II_V_V_U;
    fifo_w32_d1_A* N_COPY_V_V_U;
    fifo_w32_d1_A* a_V_V_U;
    fifo_w32_d1_A* b_V_V_U;
    fifo_w32_d1_A* mean_A_V_V_U;
    fifo_w32_d1_A* mean_B_V_V_U;
    start_for_computecUB* start_for_computecUB_U;
    start_for_boxfiltcVB* start_for_boxfiltcVB_U;
    start_for_boxfiltcWB* start_for_boxfiltcWB_U;
    sc_signal< sc_logic > boxfilter200205_U0_ap_start;
    sc_signal< sc_logic > boxfilter200205_U0_ap_done;
    sc_signal< sc_logic > boxfilter200205_U0_ap_continue;
    sc_signal< sc_logic > boxfilter200205_U0_ap_idle;
    sc_signal< sc_logic > boxfilter200205_U0_ap_ready;
    sc_signal< sc_logic > boxfilter200205_U0_start_out;
    sc_signal< sc_logic > boxfilter200205_U0_start_write;
    sc_signal< sc_logic > boxfilter200205_U0_ONES_V_V_read;
    sc_signal< sc_lv<32> > boxfilter200205_U0_N_V_V_din;
    sc_signal< sc_logic > boxfilter200205_U0_N_V_V_write;
    sc_signal< sc_logic > boxfilter201206_U0_ap_start;
    sc_signal< sc_logic > boxfilter201206_U0_ap_done;
    sc_signal< sc_logic > boxfilter201206_U0_ap_continue;
    sc_signal< sc_logic > boxfilter201206_U0_ap_idle;
    sc_signal< sc_logic > boxfilter201206_U0_ap_ready;
    sc_signal< sc_logic > boxfilter201206_U0_I_V_V_read;
    sc_signal< sc_lv<32> > boxfilter201206_U0_mean_I_V_V_din;
    sc_signal< sc_logic > boxfilter201206_U0_mean_I_V_V_write;
    sc_signal< sc_logic > boxfilter202207_U0_ap_start;
    sc_signal< sc_logic > boxfilter202207_U0_ap_done;
    sc_signal< sc_logic > boxfilter202207_U0_ap_continue;
    sc_signal< sc_logic > boxfilter202207_U0_ap_idle;
    sc_signal< sc_logic > boxfilter202207_U0_ap_ready;
    sc_signal< sc_logic > boxfilter202207_U0_I_2_V_V_read;
    sc_signal< sc_lv<32> > boxfilter202207_U0_mean_II_V_V_din;
    sc_signal< sc_logic > boxfilter202207_U0_mean_II_V_V_write;
    sc_signal< sc_logic > compute_a_b208_U0_ap_start;
    sc_signal< sc_logic > compute_a_b208_U0_start_full_n;
    sc_signal< sc_logic > compute_a_b208_U0_ap_done;
    sc_signal< sc_logic > compute_a_b208_U0_ap_continue;
    sc_signal< sc_logic > compute_a_b208_U0_ap_idle;
    sc_signal< sc_logic > compute_a_b208_U0_ap_ready;
    sc_signal< sc_logic > compute_a_b208_U0_start_out;
    sc_signal< sc_logic > compute_a_b208_U0_start_write;
    sc_signal< sc_logic > compute_a_b208_U0_N_V_V_read;
    sc_signal< sc_lv<32> > compute_a_b208_U0_N_COPY_V_V_din;
    sc_signal< sc_logic > compute_a_b208_U0_N_COPY_V_V_write;
    sc_signal< sc_logic > compute_a_b208_U0_mean_I_V_V_read;
    sc_signal< sc_logic > compute_a_b208_U0_mean_II_V_V_read;
    sc_signal< sc_lv<32> > compute_a_b208_U0_a_V_V_din;
    sc_signal< sc_logic > compute_a_b208_U0_a_V_V_write;
    sc_signal< sc_lv<32> > compute_a_b208_U0_b_V_V_din;
    sc_signal< sc_logic > compute_a_b208_U0_b_V_V_write;
    sc_signal< sc_logic > boxfilter203209_U0_ap_start;
    sc_signal< sc_logic > boxfilter203209_U0_ap_done;
    sc_signal< sc_logic > boxfilter203209_U0_ap_continue;
    sc_signal< sc_logic > boxfilter203209_U0_ap_idle;
    sc_signal< sc_logic > boxfilter203209_U0_ap_ready;
    sc_signal< sc_logic > boxfilter203209_U0_a_V_V_read;
    sc_signal< sc_lv<32> > boxfilter203209_U0_mean_A_V_V_din;
    sc_signal< sc_logic > boxfilter203209_U0_mean_A_V_V_write;
    sc_signal< sc_logic > boxfilter210_U0_ap_start;
    sc_signal< sc_logic > boxfilter210_U0_ap_done;
    sc_signal< sc_logic > boxfilter210_U0_ap_continue;
    sc_signal< sc_logic > boxfilter210_U0_ap_idle;
    sc_signal< sc_logic > boxfilter210_U0_ap_ready;
    sc_signal< sc_logic > boxfilter210_U0_b_V_V_read;
    sc_signal< sc_lv<32> > boxfilter210_U0_mean_B_V_V_din;
    sc_signal< sc_logic > boxfilter210_U0_mean_B_V_V_write;
    sc_signal< sc_logic > compute_I_enhanced21_U0_ap_start;
    sc_signal< sc_logic > compute_I_enhanced21_U0_ap_done;
    sc_signal< sc_logic > compute_I_enhanced21_U0_ap_continue;
    sc_signal< sc_logic > compute_I_enhanced21_U0_ap_idle;
    sc_signal< sc_logic > compute_I_enhanced21_U0_ap_ready;
    sc_signal< sc_lv<16> > compute_I_enhanced21_U0_I_enhanced_data_stream_V_din;
    sc_signal< sc_logic > compute_I_enhanced21_U0_I_enhanced_data_stream_V_write;
    sc_signal< sc_logic > compute_I_enhanced21_U0_mean_A_V_V_read;
    sc_signal< sc_logic > compute_I_enhanced21_U0_mean_B_V_V_read;
    sc_signal< sc_logic > compute_I_enhanced21_U0_N_COPY_V_V_read;
    sc_signal< sc_logic > compute_I_enhanced21_U0_I_COPY_V_V_read;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > N_V_V_full_n;
    sc_signal< sc_lv<32> > N_V_V_dout;
    sc_signal< sc_logic > N_V_V_empty_n;
    sc_signal< sc_logic > mean_I_V_V_full_n;
    sc_signal< sc_lv<32> > mean_I_V_V_dout;
    sc_signal< sc_logic > mean_I_V_V_empty_n;
    sc_signal< sc_logic > mean_II_V_V_full_n;
    sc_signal< sc_lv<32> > mean_II_V_V_dout;
    sc_signal< sc_logic > mean_II_V_V_empty_n;
    sc_signal< sc_logic > N_COPY_V_V_full_n;
    sc_signal< sc_lv<32> > N_COPY_V_V_dout;
    sc_signal< sc_logic > N_COPY_V_V_empty_n;
    sc_signal< sc_logic > a_V_V_full_n;
    sc_signal< sc_lv<32> > a_V_V_dout;
    sc_signal< sc_logic > a_V_V_empty_n;
    sc_signal< sc_logic > b_V_V_full_n;
    sc_signal< sc_lv<32> > b_V_V_dout;
    sc_signal< sc_logic > b_V_V_empty_n;
    sc_signal< sc_logic > mean_A_V_V_full_n;
    sc_signal< sc_lv<32> > mean_A_V_V_dout;
    sc_signal< sc_logic > mean_A_V_V_empty_n;
    sc_signal< sc_logic > mean_B_V_V_full_n;
    sc_signal< sc_lv<32> > mean_B_V_V_dout;
    sc_signal< sc_logic > mean_B_V_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_boxfilter200205_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_boxfilter200205_U0_ap_ready;
    sc_signal< sc_lv<2> > boxfilter200205_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_boxfilter201206_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_boxfilter201206_U0_ap_ready;
    sc_signal< sc_lv<2> > boxfilter201206_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_boxfilter202207_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_boxfilter202207_U0_ap_ready;
    sc_signal< sc_lv<2> > boxfilter202207_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_compute_I_enhanced21_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_compute_I_enhanced21_U0_ap_ready;
    sc_signal< sc_lv<2> > compute_I_enhanced21_U0_ap_ready_count;
    sc_signal< sc_lv<1> > start_for_compute_a_b208_U0_din;
    sc_signal< sc_logic > start_for_compute_a_b208_U0_full_n;
    sc_signal< sc_lv<1> > start_for_compute_a_b208_U0_dout;
    sc_signal< sc_logic > start_for_compute_a_b208_U0_empty_n;
    sc_signal< sc_logic > boxfilter201206_U0_start_full_n;
    sc_signal< sc_logic > boxfilter201206_U0_start_write;
    sc_signal< sc_logic > boxfilter202207_U0_start_full_n;
    sc_signal< sc_logic > boxfilter202207_U0_start_write;
    sc_signal< sc_lv<1> > start_for_boxfilter203209_U0_din;
    sc_signal< sc_logic > start_for_boxfilter203209_U0_full_n;
    sc_signal< sc_lv<1> > start_for_boxfilter203209_U0_dout;
    sc_signal< sc_logic > start_for_boxfilter203209_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_boxfilter210_U0_din;
    sc_signal< sc_logic > start_for_boxfilter210_U0_full_n;
    sc_signal< sc_lv<1> > start_for_boxfilter210_U0_dout;
    sc_signal< sc_logic > start_for_boxfilter210_U0_empty_n;
    sc_signal< sc_logic > boxfilter203209_U0_start_full_n;
    sc_signal< sc_logic > boxfilter203209_U0_start_write;
    sc_signal< sc_logic > boxfilter210_U0_start_full_n;
    sc_signal< sc_logic > boxfilter210_U0_start_write;
    sc_signal< sc_logic > compute_I_enhanced21_U0_start_full_n;
    sc_signal< sc_logic > compute_I_enhanced21_U0_start_write;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_I_2_V_V_read();
    void thread_I_COPY_V_V_read();
    void thread_I_V_V_read();
    void thread_I_enhanced_data_stream_V_din();
    void thread_I_enhanced_data_stream_V_write();
    void thread_ONES_V_V_read();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_boxfilter200205_U0_ap_ready();
    void thread_ap_sync_boxfilter201206_U0_ap_ready();
    void thread_ap_sync_boxfilter202207_U0_ap_ready();
    void thread_ap_sync_compute_I_enhanced21_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_boxfilter200205_U0_ap_continue();
    void thread_boxfilter200205_U0_ap_start();
    void thread_boxfilter201206_U0_ap_continue();
    void thread_boxfilter201206_U0_ap_start();
    void thread_boxfilter201206_U0_start_full_n();
    void thread_boxfilter201206_U0_start_write();
    void thread_boxfilter202207_U0_ap_continue();
    void thread_boxfilter202207_U0_ap_start();
    void thread_boxfilter202207_U0_start_full_n();
    void thread_boxfilter202207_U0_start_write();
    void thread_boxfilter203209_U0_ap_continue();
    void thread_boxfilter203209_U0_ap_start();
    void thread_boxfilter203209_U0_start_full_n();
    void thread_boxfilter203209_U0_start_write();
    void thread_boxfilter210_U0_ap_continue();
    void thread_boxfilter210_U0_ap_start();
    void thread_boxfilter210_U0_start_full_n();
    void thread_boxfilter210_U0_start_write();
    void thread_compute_I_enhanced21_U0_ap_continue();
    void thread_compute_I_enhanced21_U0_ap_start();
    void thread_compute_I_enhanced21_U0_start_full_n();
    void thread_compute_I_enhanced21_U0_start_write();
    void thread_compute_a_b208_U0_ap_continue();
    void thread_compute_a_b208_U0_ap_start();
    void thread_compute_a_b208_U0_start_full_n();
    void thread_start_for_boxfilter203209_U0_din();
    void thread_start_for_boxfilter210_U0_din();
    void thread_start_for_compute_a_b208_U0_din();
};

}

using namespace ap_rtl;

#endif
